apiVersion: v2
name: nebari-mlflow-pack
description: A Helm chart for deploying MLflow on Kubernetes with optional Nebari platform integration
type: application
version: 0.2.1
appVersion: "3.7.0"

dependencies:
  - name: mlflow
    version: 1.8.1
    repository: https://community-charts.github.io/helm-charts
