{{- if .Values.nebariapp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nebari-mlflow-allowed-hosts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-mlflow-pack.labels" . | nindent 4 }}
type: Opaque
stringData:
  MLFLOW_SERVER_ALLOWED_HOSTS: {{ include "nebari-mlflow-pack.allowed-hosts" . | quote }}
{{- end }}
